// This file is generated by Diesel, do not edit manually.
table! {
    users (id) {
        id -> Int4,
        name -> Varchar,
        email -> Varchar,
        vip_level -> VarChar,
        new_user -> Bool
    }
}